# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: clj-holmes

on:
  push:
    branches: [ base ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ base ]
  schedule:
    - cron: '17 17 * * 4'

permissions:
  contents: read
  
jobs:
  clj-holmes:
    name: Run clj-holmes scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan code
        uses: clj-holmes/clj-holmes-action@92d59ed56e48c0e9ffd7ae39bf700b1b1959cc11
        with:
          rules-repository: 'git://org/private-rules-repo#main'
          output-type: 'sarif'
          output-file: 'clj-holmes-results.sarif'
          fail-on-result: 'false'

      - name: Upload analysis results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{github.workspace}}/clj-holmes-results.sarif
          ait-for-processing: true
