- name: GitHub action for Wolfram language
  on: [push]
  run_wolfram:
    name: wolfram github actions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Wolfram script
      uses: miRoox/wolfram-action@f024f844662fbc49994634a8966c8d1bfeb73f2d
      with:
  - name: IOL Runner
      with:
    file: IOL.wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
  - name: Function2 for PocketPinball Runner
    file: Function2 for PocketPinball.wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
        
  - name: IOL at Pi for Delta and Theta Runner
      with:
    file: IOL at Pi for Delta and Theta.wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    
  - name: IOL where x is 1 to 100 Runner
      with:
    file: IOL where x is 1 to 100.wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    
  - name: IOL where y is .0001 or .56 Runner
      with:
    file: IOL where y is .0001 or .56.wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    
  - name: IOL where y is 1 to 100(Copy) Runner
      with:
    file: IOL where y is 1 to 100(Copy).wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    
  - name: IOL where y is 1 to 100 Runner
      with:
    file: IOL where y is 1 to 100.wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    
  - name: IOL with x and y as Value Metrics Runner
      with:
    file: IOL with x and y as Value Metrics.wl
        args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
  - name: PinBall Function (Part 2) Runner
      with:
    file: PinBall Function (Part 2).wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
        
  - name: PinBoard Function (Cont.) Runner
      with:
    file: PinBoard Function (Cont.).wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
        
  - name: PinBoard Function Runner
      with:
    file: PinBoard Function.wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
        
  - name: Pocket Pinball Matrix Runner
      with:
    file: Pocket Pinball Matrix.wl
    args:
      run
    args:
      0 1 0 function-IOL var-IOL 
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
